/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Binary, ContractInfo, Uint128 } from "../../../shared/contract/types";
import { AMMPair, ContractInstantiationInfo, StakingContractInit, TokenPair, TokenType } from "../../common_types";
import { AMMSettings } from "./common_types";


export type ExecuteMsg =
  | Set_config_msg
  | Create_a_m_m_pair_msg
  | Add_a_m_m_pairs_msg
  ;
// Individual Msgs
export interface Set_config_msg {
  set_config: {
    admin_auth?: ContractInfo | null;
    amm_settings?: AMMSettings | null;
    api_key?: string | null;
    lp_token_contract?: ContractInstantiationInfo | null;
    pair_contract?: ContractInstantiationInfo | null;
    [k: string]: unknown;
  };
}
export interface Create_a_m_m_pair_msg {
  create_a_m_m_pair: {
    amm_pair_custom_label?: string | null;
    entropy: Binary;
    lp_token_custom_label?: string | null;
    lp_token_decimals: number;
    pair: TokenPair;
    staking_contract?: StakingContractInit | null;
    [k: string]: unknown;
  };
}
export interface Add_a_m_m_pairs_msg {
  add_a_m_m_pairs: {
    amm_pairs: AMMPair[];
    [k: string]: unknown;
  };
}