/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Pagination, TokenPair } from "../../common_types";

export type QueryMsg =
  | List_a_m_m_pairs_msg
  | Get_a_m_m_pair_address_msg
  | Get_config_msg
  | Authorize_api_key_msg
  ;

export interface List_a_m_m_pairs_msg {
  list_a_m_m_pairs: {
    pagination: Pagination;
    [k: string]: unknown;
  };
}
export interface Get_a_m_m_pair_address_msg {
  get_a_m_m_pair_address: {
    pair: TokenPair;
    [k: string]: unknown;
  };
}
export interface Get_config_msg {
  get_config: {
    [k: string]: unknown;
  };
}
export interface Authorize_api_key_msg {
  authorize_api_key: {
    api_key: string;
    [k: string]: unknown;
  };
}

