/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { AMMPair, ContractInstantiationInfo } from "../../common_types";
import { AMMSettings } from "./common_types";
import { ContractInfo } from "../../../shared/contract/types";


export type QueryResponse =
  | List_a_m_m_pairs_response
  | Get_config_response
  | Get_a_m_m_pair_address_response
  | Authorize_api_key_response
  ;
export interface List_a_m_m_pairs_response {
  list_a_m_m_pairs: {
    amm_pairs: AMMPair[];
    [k: string]: unknown;
  };
}
export interface Get_config_response {
  get_config: {
    admin_auth: ContractInfo;
    amm_settings: AMMSettings;
    authenticator?: ContractInfo | null;
    lp_token_contract: ContractInstantiationInfo;
    pair_contract: ContractInstantiationInfo;
    [k: string]: unknown;
  };
}
export interface Get_a_m_m_pair_address_response {
  get_a_m_m_pair_address: {
    address: string;
    [k: string]: unknown;
  };
}
export interface Authorize_api_key_response {
  authorize_api_key: {
    authorized: boolean;
    [k: string]: unknown;
  };
}