/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Binary, ContractInfo } from "../../../../modules/shared/contract/types";
import { CustomFee } from "./common_types";
import { ContractInstantiationInfo, StakingContractInit, TokenPair } from "../../common_types";



export interface InitMsg {
  admin_auth: ContractInfo;
  arbitrage_contract?: ContractInfo | null;
  custom_fee?: CustomFee | null;
  entropy: Binary;
  factory_info?: ContractInfo | null;
  lp_token_contract: ContractInstantiationInfo;
  lp_token_custom_label?: string | null;
  lp_token_decimals: number;
  pair: TokenPair;
  prng_seed: Binary;
  staking_contract?: StakingContractInit | null;
  [k: string]: unknown;
}



