/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Addr } from "../../../../modules/shared/contract/types";
import { TokenPairAmount } from "./common_types";
import { Pagination, TokenAmount } from "../../common_types";

export type QueryMsg =
  | Get_config_msg
  | Get_pair_info_msg
  | Get_trade_history_msg
  | Get_white_list_address_msg
  | Get_trade_count_msg
  | Swap_simulation_msg
  | Get_shade_dao_info_msg
  | Get_estimated_liquidity_msg
  ;


// Individual Queries
export interface Get_config_msg {
  get_config: {
    [k: string]: unknown;
  };
}
export interface Get_pair_info_msg {
  get_pair_info: {
    [k: string]: unknown;
  };
}
export interface Get_trade_history_msg {
  get_trade_history: {
    api_key: string;
    pagination: Pagination;
    [k: string]: unknown;
  };
}
export interface Get_white_list_address_msg {
  get_white_list_address: {
    [k: string]: unknown;
  };
}
export interface Get_trade_count_msg {
  get_trade_count: {
    [k: string]: unknown;
  };
}
export interface Swap_simulation_msg {
  swap_simulation: {
    exclude_fee?: boolean | null;
    offer: TokenAmount;
    [k: string]: unknown;
  };
}
export interface Get_shade_dao_info_msg {
  get_shade_dao_info: {
    [k: string]: unknown;
  };
}
export interface Get_estimated_liquidity_msg {
  get_estimated_liquidity: {
    deposit: TokenPairAmount;
    execute_sslp_virtual_swap?: boolean | null;
    sender: Addr;
    [k: string]: unknown;
  };
}
