/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | Get_config_msg
  | Get_admins_msg
  | Get_permissions_msg
  | Validate_admin_permission_msg
  ;


// individual types
export interface Get_config_msg {
  get_config: {};
}
export interface Get_admins_msg {
  get_admins: {};
}
export interface Get_permissions_msg {
  get_permissions: {
    user: string;
  };
}
export interface Validate_admin_permission_msg {
  validate_admin_permission: {
    permission: string;
    user: string;
  };
}