/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { TokenAmount } from "../../common_types";
import { Hop } from "./common_types";

export type QueryMsg =
  | Swap_simulation_msg
  | Get_config_msg
  ;
export interface Swap_simulation_msg {
  swap_simulation: {
    exclude_fee?: boolean | null;
    offer: TokenAmount;
    path: Hop[];
    [k: string]: unknown;
  };
}
export interface Get_config_msg {
  get_config: {
    [k: string]: unknown;
  };
}