/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Binary, ContractInfo } from "../../../shared/contract/types";
import { ContractInstantiationInfo } from "../../common_types";
import { AMMSettings } from "./common_types";


export interface InitMsg {
  admin_auth: ContractInfo;
  amm_settings: AMMSettings;
  api_key: string;
  authenticator?: ContractInfo | null;
  lp_token_contract: ContractInstantiationInfo;
  pair_contract: ContractInstantiationInfo;
  prng_seed: Binary;
  [k: string]: unknown;
}