[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = '0.8.19'
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

base = "https://mainnet.base.org"
base-sepolia = "https://base-sepolia-rpc.publicnode.com"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 80
multiline_func_header = "params_first"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
